# TWITTER API CREDENTIALS
BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAACAncQEAAAAA9cYB3KV8g%2BLqQh58o6Zys2gaSr0%3DvWYDLrPbO3lO9G2fwVCGFbgSQ1mJH8TL1sgMrCM6fAsCg0x3rg"  # Your Twitter Bearer Token Credential string

